version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - rm -rf cdk.out
      - npx cdk synth
      - ls -lR cdk.out
artifacts:
  base-directory: cdk.out
  files:
    - '**/*'