version: 0.2
phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - npx cdk synth
      - npx cdk deploy --require-approval never
artifacts:
  base-directory: cdk.out
  files:
    - MyCdkProjectStack.template.json
    - '**/*' 